Apply machine configs only if template files exist
Currently it's failing because there are no worker templates:
error: the path "./assets/post-install/*-worker.yaml" does not exist
Also export KUBECONFIG env var.